import React from "react";
import { Link } from "react-router-dom";
const Home= () => {
  return (
    <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}>
      <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
      <p style={{ fontSize: "18px", marginBottom: "30px" }}>
        This project was generated By{" "}
        <a href="#" style={{ color: "#87CEFA", textDecoration: "none" }}>
          Geet Tourism
        </a>
        . Quickly use below links to navigate through all pages.
      </p>
      <ul style={{ listStyle: "none", padding: "0" }}>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Home
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/aboutus" style={{ color: "#87CEFA", textDecoration: "none" }}>
            AboutUs
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/spot" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Spot
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/spotdetails" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Spot details
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/contactpage" style={{ color: "#87CEFA", textDecoration: "none" }}>
            ContactPage
          </Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
